name: tests

on: [push]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'windows-2022'
          - 'windows-2019'
        python:
          - '3.10'
          - '3.9'
          - '3.8'
          - '3.7'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Test PyAV wheels
        run: |
          pip install av
          python -c "import av; print(av.__version__)"
